### PR TITLE
Tree sortable

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
@gkoz: Works way better with the "normal" usage of `TreeSortable`. I had to do some dark magic (not `TreeSortable` linked), I'll keep it that way for the moment.

**Comment by gkoz** [comment]
But it did work, only required getting rid of the closure and simply calling `set_sort_column_id` at the UI initialization time.

**Comment by GuillaumeGomez** [comment]
Some columns had to be sorted in a specific way so I couldn't keep the default sort function.

**Comment by gkoz** [comment]
So you needed to set sort functions for some columns. Why reimplement what `TreeViewCoumn` already does fine?

**Comment by GuillaumeGomez** [comment]
Because of weird behavior. If not set, you have to click twice on a column header to be able to have the sorting working.

**Comment by gkoz** [comment]
That's because you're misusing it. `TreeViewColumn::set_sort_column_id` needs to be called at initialization time not in a click handler.

**Comment by GuillaumeGomez** [comment]
Oh! Interesting. Thanks for the tip!

**Pull request merged**
