### PR TITLE
clippy: allow two warnings

### PR DESCRIPTION
**Pull request by tuncer**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks! Just waiting for CI and then I merge.

**Comment by tuncer** [comment]
Changed travis config to always run clippy.

**Comment by GuillaumeGomez** [comment]
I'd rather not have clippy run all the time. I think on nightly is enough since it's time consuming (not much but travis tend to be quite slow...).

**Comment by tuncer** [comment]
Sure, dropped that commit.

**Pull request merged**
