### PR TITLE
Adding some install and build instructions.

### PR DESCRIPTION
**Pull request by deckarep**
Added OSX install instructions.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks!

However, I just had to install gtk+3, not the rest. Strange. :-/

**Comment by deckarep** [comment]
Hmm, this is what I had to do on a fresh Mac running OSX 10.11 El Capitan.

I'll try again just installing the one you did to see if it installs the rest by default and update the docs then.

**Comment by GuillaumeGomez** [comment]
Thanks! :)

**Comment by GuillaumeGomez** [comment]
I'll close this PR. If it's still required, can you please send another one?

**Pull request closed without merging**
